version: '3'
services:
  db:
    image: postgres:14.4-alpine
    container_name: database-go
    restart: always
    ports:
      - "6432:5432"
    environment:
      POSTGRES_PASSWORD: GormPass
      POSTGRES_DB: goland
      POSTGRES_USER: ramon
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin-container
    ports:
      - 8080:8080
    environment:
      PGADMIN_DEFAULT_EMAIL: correo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: supersecret
volumes:
  db:
